### ISSUE TITLE
Define database and add to the ReadME

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/magic-link#7]
Define which database we're going to use for storing the confirmed votes(JWT), current poll options, current poll results.

**Confirmed votes payload**
```
{
  "options": ["PHP", "JAVA", "Python"],
  "identifier": "email@domain.com"
}
```
**Vote stored**
```
_id: identifier hash
vote: payload
```
_Note: Each vote is transformed into a [JWT](https://jwt.io/) and stored in the database._

**Current Poll options**
```
{
  "options": ["PHP", "JAVA", "Python"]
}
```

**Current Poll result**
```
{
  "result": "Python"
}
```

**Comment by ArthurFleischman** [comment]
first, do you guys prefer sql or nosql?

**Comment by ArthurFleischman** [comment]
my opinion is to use mysql, pretty simple and straight forward...

**Comment by mateushnsoares** [comment]
I prefer NoSQL, because the project does not need many correlations. I think a [MongoDB ](https://www.mongodb.com/) is a good idea and use [MongoDB Atlas](https://www.mongodb.com/cloud/atlas/signup)  to facilitate utilization is also a good idea and about the library to manipulate the database that I'm thinking of  [PyMongo ](https://pymongo.readthedocs.io/en/stable/)  but I will look for more.

**Comment by ArthurFleischman** [comment]
@MateusSoares895 nice opportunity for me to learn nosql... never needed ....

**Comment by daviziks** [comment]
So, guys, I believe that the best option for the project will be the [Firebase](https://firebase.google.com/docs/database/rest/start), the Firebase documentation itself teaches how to configure with REST APIs integrated with real-time. Another lib that also helps a lot is the [pyFirebase](https://pypi.org/project/python-firebase/). I've seen projects implementing and it looks great. I agree with @MateusSoares895 not to use SQL because the project does not have many relationships, NoSQL would speed up a lot since we only have **12 hours**.

**Comment by jbarbosaamancio** [comment]
This project is a good opportunity for used NoSQL and to me learn NoSQL

**Comment by mateushnsoares** [comment]
@jbarbosaamancio  and @ArthurFleischman  the nosql databases are a good idea when we don't have many relationships because it helps to speed up and facilitate the coding, simplifying the code

**Comment by ArthurFleischman** [comment]
> So, guys, I believe that the best option for the project will be the [Firebase](https://firebase.google.com/docs/database/rest/start), the Firebase documentation itself teaches how to configure with REST APIs integrated with real-time. Another lib that also helps a lot is the [pyFirebase](https://pypi.org/project/python-firebase/). I've seen projects implementing and it looks great. I agree with @MateusSoares895 not to use SQL because the project does not have many relationships, NoSQL would speed up a lot since we only have **12 hours**.

no, the goal here is "learn python" not "make it work"....

**Comment by nataneb32** [comment]
MongoDB. It's easier to use than MySql in Python. If we use SQL we would need to implement migration and since we are using flask, that different from Django, doesn't have a ready for work implementaion of database let's use MongoDB.

**Comment by lucasmontano** [comment]
We don't need relations between entities, so we don't need a relational database. NoSQL sounds like a better option here.

In the first edition of #umaStackQueNaoDomino we choose MongoDB, it's free to use on Heroku. As we're going to keep using Heroku in the second edition, I think it makes sense to use MongoDB again.

**Comment by omurilo** [comment]
According @codeshow pyMongo not is asynchronous and as the Fast API is, I think we will need to find an alternative noSQL that is asynchronous.

**Comment by daviziks** [comment]
@omurilo So, between Firebase or MongoDB, for this project, which is the best? I think Firebase is asynchronous ...

**Comment by jbarbosaamancio** [comment]
May if use async functions with MongoDB in the Python see in this link [Async/await MongoDB in Python](https://dev.to/svenvarkel/async-await-mongodb-in-python-25bk)
